name: CI

push:
  branches:
    - master
pull_request:
  branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the gatling test
        run: |
          echo running gatling
          ./test/bin/gatling.sh -s commandTest.TestSimulation
